### ISSUE TITLE
feature: Implementar crypto en cuotas

### ISSUE THREAD

**Issue by MateoCerquetella** [ferminrp/meli-to-crypto#14]
Podriamos implementar las cuotas en las cryptos para tener mejor vision lo que saldría en cuotas

Antes:
<img width="339" alt="Screen Shot 2022-03-16 at 10 10 42 AM" src="https://user-images.githubusercontent.com/33433649/158597196-a6b15857-3820-4118-afc3-446a7d05a04a.png">

Despues:
<img width="339" alt="Screen Shot 2022-03-16 at 10 11 53 AM" src="https://user-images.githubusercontent.com/33433649/158597394-7ebf254b-628d-463e-9673-5bdb266d76c8.png">

**Comment by juansegnana** [comment]
Sip, lo agarro cuando pueda. 
Habría que mejorar los selectores. Me parece que el precio normal y el de cuotas tienen el mismo selector
