### ISSUE TITLE
Merge a master

### ISSUE THREAD

**Issue by andresgardiol** [ferminrp/meli-to-crypto#21]
Buenas! 
Vi un monton de nuevas features tremendas, cuándo las vamos a mergear a master para hacer un release?

**Comment by juansegnana** [comment]
Esto estaba por preguntar! Ahora creo PR, si a todos les parece bien ya queda en `main`.

**Comment by ferminrp** [comment]
Hace 10 dias que esta una version en review. En cuanto pase esa mando de vuelta main.
